- name: Deploy Docker App
  hosts: remote
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: Pull latest code
      git:
        repo: https://github.com/adeelumar-17/mydevops.git
        dest: /home/deployer/app
        force: yes

    - name: Run Docker container
      shell: |
        docker stop myapp || true
        docker rm myapp || true
        docker build -t myapp /home/deployer/app/app
        docker run -d -p 3000:3000 --name myapp myapp
