name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'app/**'           # Only run when something in /app changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Use ssh-keyscan to get the host's public key
          ssh-keyscan -H homedevserver.ddns.net >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          sudo apt update && sudo apt install ansible -y
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
